const https = require('https');

const GITHUB_USER = '123maria0608-star';

function ghRequest(method, endpoint, body, token) {
  return new Promise((resolve, reject) => {
    const data = body ? JSON.stringify(body) : null;
    const req  = https.request({
      hostname: 'api.github.com',
      path:     endpoint.startsWith('/') ? endpoint : `/${endpoint}`,
      method,
      headers: {
        'Authorization': `token ${token}`,
        'Accept':        'application/vnd.github.v3+json',
        'Content-Type':  'application/json',
        'User-Agent':    'website-generator/1.0',
        ...(data ? { 'Content-Length': Buffer.byteLength(data) } : {}),
      },
    }, (res) => {
      let out = '';
      res.on('data', c => out += c);
      res.on('end', () => {
        try {
          const parsed = out ? JSON.parse(out) : {};
          if (res.statusCode >= 400) reject(new Error(parsed.message || `GitHub API ${res.statusCode}`));
          else resolve(parsed);
        } catch (e) { resolve({}); }
      });
    });
    req.on('error', reject);
    if (data) req.write(data);
    req.end();
  });
}

// Shorthand wrappers with correct path prefix
function ghPost(path, body, token)  { return ghRequest('POST',  path, body, token); }
function ghPatch(path, body, token) { return ghRequest('PATCH', path, body, token); }
function ghGet(path, token)         { return ghRequest('GET',   path, null, token); }

function wait(ms) { return new Promise(r => setTimeout(r, ms)); }

async function pushSiteToGitHub(repoName, files, token) {
  // 1. Create repo
  await ghPost('/user/repos', {
    name:        repoName,
    description: `Generated by website-generator`,
    private:     false,
    auto_init:   true,
  }, token).catch(() => {}); // ignore if already exists

  await wait(3000); // let GitHub initialize

  // 2. Get HEAD commit SHA
  let ref;
  for (let i = 0; i < 5; i++) {
    try {
      ref = await ghGet(`/repos/${GITHUB_USER}/${repoName}/git/ref/heads/main`, token);
      break;
    } catch (_) {
      await wait(2000);
    }
  }
  if (!ref) throw new Error('Could not get repo HEAD ref after retries');

  const headSha   = ref.object.sha;
  const headCommit = await ghGet(`/repos/${GITHUB_USER}/${repoName}/git/commits/${headSha}`, token);
  const baseTreeSha = headCommit.tree.sha;

  // 3. Create blobs for every file
  const treeItems = [];
  for (const [filePath, content] of Object.entries(files)) {
    const base64 = Buffer.isBuffer(content) ? content.toString('base64') : Buffer.from(content).toString('base64');
    const blob   = await ghPost(`/repos/${GITHUB_USER}/${repoName}/git/blobs`, {
      content:  base64,
      encoding: 'base64',
    }, token);
    treeItems.push({ path: filePath, mode: '100644', type: 'blob', sha: blob.sha });
  }

  // 4. Create new tree
  const newTree = await ghPost(`/repos/${GITHUB_USER}/${repoName}/git/trees`, {
    base_tree: baseTreeSha,
    tree:      treeItems,
  }, token);

  // 5. Create commit
  const newCommit = await ghPost(`/repos/${GITHUB_USER}/${repoName}/git/commits`, {
    message: `Deploy ${repoName}`,
    tree:    newTree.sha,
    parents: [headSha],
  }, token);

  // 6. Update branch ref
  await ghPatch(`/repos/${GITHUB_USER}/${repoName}/git/refs/heads/main`, {
    sha: newCommit.sha,
  }, token);

  // 7. Enable GitHub Pages
  await ghPost(`/repos/${GITHUB_USER}/${repoName}/pages`, {
    source: { branch: 'main', path: '/' },
  }, token).catch(() => {}); // ignore if already enabled

  return {
    repoUrl:  `https://github.com/${GITHUB_USER}/${repoName}`,
    liveUrl:  `https://${GITHUB_USER}.github.io/${repoName}/`,
  };
}

module.exports = { pushSiteToGitHub, GITHUB_USER };
